import Head from 'next/head'

// Components 
import Hero from '../components/Hero/hero'
import NavBar from '../components/nav/nav'



export default function Home() {
  return (
    <div >

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav >
        <NavBar />
      </nav>

      <main >
        <Hero />
      </main>

      <footer>
        
      </footer>
    </div>
  )
}
